/* ================= FOOD ALCHEMY LAB — COMPOUND DATA =================
   115 compounds total: 33 "core" (shown by default, like a compact
   periodic table) + 82 "extended" (revealed with the toggle).
   Molar masses are standard values for small molecules; large
   biopolymers (starches, proteins, gums) don't have one fixed molar
   mass, so those are marked "Variable (polymer)".
   ======================================================================= */

const CATEGORY_META = {
  starch:       { label:'Starch',            color:'#C97A2E' },
  protein:      { label:'Protein',           color:'#B5583A' },
  lipid:        { label:'Lipid',             color:'#D8B25C' },
  acid:         { label:'Acid',              color:'#2FE6C9' },
  salt:         { label:'Salt',              color:'#8FA6B8' },
  sugar:        { label:'Sugar',             color:'#E39B9B' },
  hydrocolloid: { label:'Hydrocolloid',      color:'#4C6B58' },
  enzyme:       { label:'Enzyme',            color:'#7FA8D9' },
  flavor:       { label:'Flavor Compound',   color:'#6B4E71' },
  preservative: { label:'Preservative',      color:'#9C8B6F' },
};

const COMPOUNDS = [
  // ============ STARCH (11: 3 core + 8 extended) ============
  { id:'amylose', name:'Amylose', symbol:'Am', category:'starch', core:true,
    formula:'(C6H10O5)n', molarMass:'162.14 g/mol / unit (polymer)',
    action:'Linear glucose chain that packs tightly and retrogrades (firms up) as it cools.',
    uses:'Responsible for the "set" in cooled rice, pasta, and bread staling.' },
  { id:'amylopectin', name:'Amylopectin', symbol:'Ap', category:'starch', core:true,
    formula:'(C6H10O5)n', molarMass:'162.14 g/mol / unit (polymer)',
    action:'Branched glucose chain that swells easily in hot water and stays softer on cooling.',
    uses:'Gives waxy rice, glutinous desserts, and thickened sauces their soft, glossy body.' },
  { id:'resistant-starch', name:'Resistant Starch', symbol:'Rs', category:'starch', core:true,
    formula:'(C6H10O5)n', molarMass:'Variable (polymer)',
    action:'Starch that recrystallizes after cooling, resisting digestion in the small intestine.',
    uses:'Forms in cooled-then-reheated rice and potatoes; also used as a fiber additive.' },
  { id:'dextrin', name:'Dextrin', symbol:'Dx', category:'starch', core:false,
    formula:'(C6H10O5)n', molarMass:'Variable (short polymer)',
    action:'Shorter starch fragments produced when starch is partially broken by heat or acid.',
    uses:'Gives toasted bread crust and pie-dough edges their light crispness.' },
  { id:'modified-corn-starch', name:'Modified Corn Starch', symbol:'Mc', category:'starch', core:false,
    formula:'(C6H10O5)n (chemically altered)', molarMass:'Variable (polymer)',
    action:'Corn starch treated to resist breakdown under heat, acid, or freeze-thaw cycles.',
    uses:'Stabilizes fruit pie fillings and frozen sauces that would otherwise weep or separate.' },
  { id:'tapioca-starch', name:'Tapioca Starch', symbol:'Tp', category:'starch', core:false,
    formula:'(C6H10O5)n', molarMass:'Variable (polymer)',
    action:'Cassava-root starch that gelatinizes clear and stretchy rather than opaque.',
    uses:'The chew in boba pearls and the glassy shine in some Southeast Asian puddings.' },
  { id:'potato-starch', name:'Potato Starch', symbol:'Po', category:'starch', core:false,
    formula:'(C6H10O5)n', molarMass:'Variable (polymer)',
    action:'Large starch granules that swell dramatically and thicken at relatively low heat.',
    uses:'A gluten-free thickener favored for its neutral flavor and glossy finish.' },
  { id:'glycogen', name:'Glycogen', symbol:'Gc', category:'starch', core:false,
    formula:'(C6H10O5)n', molarMass:'Variable (polymer)',
    action:'Animal starch stored in liver and muscle, structurally similar to amylopectin.',
    uses:'Depleted glycogen is part of why aged, rested meat tastes different from fresh-killed.' },
  { id:'maltodextrin', name:'Maltodextrin', symbol:'Md', category:'starch', core:false,
    formula:'(C6H10O5)n', molarMass:'Variable (short polymer)',
    action:'Very short starch chains that dissolve instantly and carry almost no sweetness.',
    uses:'Used to turn fats and oils into free-flowing powders in molecular kitchens.' },
  { id:'pregelatinized-starch', name:'Pregelatinized Starch', symbol:'Pg', category:'starch', core:false,
    formula:'(C6H10O5)n (precooked)', molarMass:'Variable (polymer)',
    action:'Starch precooked and dried so it thickens in cold liquid without further heating.',
    uses:'Instant pudding mixes and no-cook pie fillings.' },
  { id:'einkorn-starch', name:'Einkorn Starch', symbol:'Ek', category:'starch', core:false,
    formula:'(C6H10O5)n', molarMass:'Variable (polymer)',
    action:'An ancient wheat starch with a lower amylopectin ratio than modern wheat.',
    uses:'Produces the denser crumb typical of Neolithic and early Bronze Age flatbreads.' },

  // ============ PROTEIN (12: 3 core + 9 extended) ============
  { id:'gluten', name:'Gluten', symbol:'Gl', category:'protein', core:true,
    formula:'Glutenin + Gliadin complex', molarMass:'Variable (polymer network)',
    action:'Kneading aligns glutenin and gliadin into an elastic, gas-trapping network.',
    uses:'Traps CO2 from yeast so bread dough rises instead of collapsing.' },
  { id:'casein', name:'Casein', symbol:'Cs', category:'protein', core:true,
    formula:'Variable phosphoprotein', molarMass:'~23,600\u201325,200 g/mol (subunits)',
    action:'Clumps into curds when milk\u2019s pH drops or rennet cleaves its stabilizing surface layer.',
    uses:'The structural protein behind every cheese, from fresh curds to aged wheels.' },
  { id:'collagen', name:'Collagen', symbol:'Co', category:'protein', core:true,
    formula:'Triple-helix polypeptide', molarMass:'~300,000 g/mol (per triple helix)',
    action:'Unwinds into gelatin under long, moist heat, releasing a silky, body-giving broth.',
    uses:'Why slow-braised short ribs and bone broth turn rich and lip-sticking when cooled.' },
  { id:'myosin', name:'Myosin', symbol:'My', category:'protein', core:false,
    formula:'Motor protein complex', molarMass:'~520,000 g/mol',
    action:'Denatures and firms starting around 50\u00b0C, then squeezes out moisture as it tightens further.',
    uses:'The main reason overcooked meat turns dry \u2014 myosin has over-contracted.' },
  { id:'actin', name:'Actin', symbol:'Ac', category:'protein', core:false,
    formula:'Globular structural protein', molarMass:'~42,000 g/mol',
    action:'Denatures at a higher temperature than myosin, around 66\u00b0C, tightening muscle fibers further.',
    uses:'Marks the point past which even slow cooking can\u2019t rescue lean cuts from toughness.' },
  { id:'beta-lactoglobulin', name:'Beta-Lactoglobulin', symbol:'Bl', category:'protein', core:false,
    formula:'Whey protein', molarMass:'~18,300 g/mol',
    action:'Unfolds under heat and links up to trap water in a fine, custardy gel.',
    uses:'Builds the set in whey-based puddings and the skin on scalded milk.' },
  { id:'ovalbumin', name:'Ovalbumin', symbol:'Ov', category:'protein', core:false,
    formula:'Egg-white glycoprotein', molarMass:'~45,000 g/mol',
    action:'Unfolds and links into a solid network between roughly 60\u201385\u00b0C.',
    uses:'The main protein responsible for egg whites setting from liquid to solid.' },
  { id:'keratin', name:'Keratin', symbol:'Kr', category:'protein', core:false,
    formula:'Fibrous structural protein', molarMass:'Variable (fibrous polymer)',
    action:'A tough, largely indigestible structural protein resistant to normal cooking heat.',
    uses:'Explains why hooves and horn require extended rendering, not simmering, to break down.' },
  { id:'elastin', name:'Elastin', symbol:'El', category:'protein', core:false,
    formula:'Elastic connective protein', molarMass:'Variable (cross-linked polymer)',
    action:'Unlike collagen, elastin barely softens with cooking \u2014 it stays rubbery at any temperature.',
    uses:'Why gristle stays chewy no matter how long a tough cut is braised.' },
  { id:'albumin', name:'Albumin', symbol:'Al', category:'protein', core:false,
    formula:'Globular serum/egg protein', molarMass:'~66,500 g/mol',
    action:'Coagulates readily with heat or acid, trapping air bubbles as it sets.',
    uses:'Stabilizes whipped egg-white foams like meringue and souffl\u00e9.' },
  { id:'zein', name:'Zein', symbol:'Ze', category:'protein', core:false,
    formula:'Corn prolamin protein', molarMass:'~22,000\u201324,000 g/mol',
    action:'A corn protein that forms a tough, glossy film when dissolved in alcohol and dried.',
    uses:'Used as an edible, moisture-resistant coating on candies and pill capsules.' },
  { id:'gliadin', name:'Gliadin', symbol:'Gi', category:'protein', core:false,
    formula:'Wheat prolamin protein', molarMass:'~30,000\u201375,000 g/mol',
    action:'The stretchy, extensible half of gluten, contributing dough\u2019s ability to expand without tearing.',
    uses:'Balances glutenin\u2019s strength to give dough both stretch and structure.' },

  // ============ LIPID (11: 3 core + 8 extended) ============
  { id:'triglyceride', name:'Triglyceride', symbol:'Tg', category:'lipid', core:true,
    formula:'Glycerol + 3 fatty acids', molarMass:'Variable (~800\u2013900 g/mol typical)',
    action:'The main storage form of dietary fat \u2014 solid or liquid depending on its fatty-acid chains.',
    uses:'Makes up nearly all cooking oils, butter, and animal fat.' },
  { id:'cholesterol', name:'Cholesterol', symbol:'Ch', category:'lipid', core:true,
    formula:'C27H46O', molarMass:'386.65 g/mol',
    action:'A rigid sterol that wedges into fat and cell membranes, adding structure.',
    uses:'Contributes to the richness and mouthfeel of egg yolk and organ meats.' },
  { id:'lecithin', name:'Lecithin', symbol:'Le', category:'lipid', core:true,
    formula:'Phosphatidylcholine', molarMass:'~750 g/mol (typical)',
    action:'Has both a water-loving and a fat-loving end, letting it bridge oil and water.',
    uses:'The natural emulsifier in egg yolk that makes mayonnaise possible.' },
  { id:'oleic-acid', name:'Oleic Acid', symbol:'Ol', category:'lipid', core:false,
    formula:'C18H34O2', molarMass:'282.46 g/mol',
    action:'A monounsaturated fatty acid that stays liquid at room temperature.',
    uses:'The dominant fatty acid in olive oil, giving it a fruity, fluid character.' },
  { id:'palmitic-acid', name:'Palmitic Acid', symbol:'Pa', category:'lipid', core:false,
    formula:'C16H32O2', molarMass:'256.43 g/mol',
    action:'A saturated fatty acid that packs tightly, raising a fat\u2019s melting point.',
    uses:'A major component of butterfat and palm oil, contributing firmness.' },
  { id:'stearic-acid', name:'Stearic Acid', symbol:'St', category:'lipid', core:false,
    formula:'C18H36O2', molarMass:'284.48 g/mol',
    action:'A long saturated fatty acid, solid well above room temperature.',
    uses:'Gives cocoa butter its clean snap and high melting point in chocolate.' },
  { id:'linoleic-acid', name:'Linoleic Acid', symbol:'Li', category:'lipid', core:false,
    formula:'C18H32O2', molarMass:'280.45 g/mol',
    action:'A polyunsaturated fatty acid prone to oxidation, especially under heat and light.',
    uses:'Abundant in sunflower and corn oil; its breakdown is why old oil smells "off."' },
  { id:'butyric-acid', name:'Butyric Acid', symbol:'Bu', category:'lipid', core:false,
    formula:'C4H8O2', molarMass:'88.11 g/mol',
    action:'A short-chain fatty acid with a sharp, pungent smell released as fat breaks down.',
    uses:'Responsible for the distinctive tang of aged Parmesan and rancid butter alike.' },
  { id:'monoglyceride', name:'Monoglyceride', symbol:'Mg', category:'lipid', core:false,
    formula:'Glycerol + 1 fatty acid', molarMass:'Variable',
    action:'An emulsifier with one fat-loving tail, produced by partially breaking down triglycerides.',
    uses:'Keeps commercial bread soft and bakery icing smooth and non-greasy.' },
  { id:'diglyceride', name:'Diglyceride', symbol:'Dg', category:'lipid', core:false,
    formula:'Glycerol + 2 fatty acids', molarMass:'Variable',
    action:'A partial breakdown product of triglycerides with intermediate emulsifying power.',
    uses:'Blended with monoglycerides to stabilize whipped toppings and margarine.' },
  { id:'phospholipid', name:'Phospholipid', symbol:'Ph', category:'lipid', core:false,
    formula:'Glycerol + 2 fatty acids + phosphate head', molarMass:'Variable (~700\u2013800 g/mol typical)',
    action:'Forms the water-fat boundary in every cell membrane and most natural emulsions.',
    uses:'The lecithin family belongs here \u2014 key to egg yolk\u2019s emulsifying power.' },

  // ============ ACID (12: 3 core + 9 extended) ============
  { id:'citric-acid', name:'Citric Acid', symbol:'Ci', category:'acid', core:true,
    formula:'C6H8O7', molarMass:'192.12 g/mol',
    action:'A triprotic acid that chelates metal ions while adding sharp, clean sourness.',
    uses:'The dominant acid in citrus fruit; also used to prevent browning in cut apples.' },
  { id:'acetic-acid', name:'Acetic Acid', symbol:'Ae', category:'acid', core:true,
    formula:'C2H4O2', molarMass:'60.05 g/mol',
    action:'Produced by bacteria oxidizing ethanol; lowers pH enough to block most spoilage microbes.',
    uses:'The active acid in vinegar, used for pickling since antiquity.' },
  { id:'lactic-acid', name:'Lactic Acid', symbol:'La', category:'acid', core:true,
    formula:'C3H6O3', molarMass:'90.08 g/mol',
    action:'Produced by bacteria fermenting sugar; curdles milk protein and tenderizes dough.',
    uses:'Behind yogurt\u2019s tang, sourdough\u2019s sourness, and kimchi\u2019s sharp edge.' },
  { id:'malic-acid', name:'Malic Acid', symbol:'Ma', category:'acid', core:false,
    formula:'C4H6O5', molarMass:'134.09 g/mol',
    action:'A tart acid that softens into lactic acid during malolactic fermentation.',
    uses:'The sharp bite in green apples and unripe grapes.' },
  { id:'tartaric-acid', name:'Tartaric Acid', symbol:'Ta', category:'acid', core:false,
    formula:'C4H6O6', molarMass:'150.09 g/mol',
    action:'Crystallizes out of cooling grape juice as tiny, harmless "wine diamonds."',
    uses:'The main acid in wine and grapes; the acid half of baking powder.' },
  { id:'ascorbic-acid', name:'Ascorbic Acid', symbol:'As', category:'acid', core:false,
    formula:'C6H8O6', molarMass:'176.12 g/mol',
    action:'A mild reducing acid that slows the enzymatic browning of cut produce.',
    uses:'Vitamin C \u2014 used to keep sliced fruit and fresh-pressed juice from oxidizing.' },
  { id:'phosphoric-acid', name:'Phosphoric Acid', symbol:'Fa', category:'acid', core:false,
    formula:'H3PO4', molarMass:'97.99 g/mol',
    action:'A strong mineral acid that adds sharp acidity without a fruity flavor.',
    uses:'Provides the tang in cola-style soft drinks.' },
  { id:'oxalic-acid', name:'Oxalic Acid', symbol:'Ox', category:'acid', core:false,
    formula:'C2H2O4', molarMass:'90.03 g/mol',
    action:'Binds calcium into insoluble crystals, giving a chalky, astringent mouthfeel in excess.',
    uses:'Naturally present in spinach and rhubarb leaves \u2014 part of why raw rhubarb leaves are toxic.' },
  { id:'succinic-acid', name:'Succinic Acid', symbol:'Su', category:'acid', core:false,
    formula:'C4H6O4', molarMass:'118.09 g/mol',
    action:'A mild acid produced during fermentation, contributing a savory-sour edge.',
    uses:'Part of what gives aged sake and some fermented sauces their rounded sourness.' },
  { id:'fumaric-acid', name:'Fumaric Acid', symbol:'Fu', category:'acid', core:false,
    formula:'C4H4O4', molarMass:'116.07 g/mol',
    action:'A stable, heat-tolerant acid that holds its sourness through baking better than citric acid.',
    uses:'Used commercially in sour candy coatings and shelf-stable baking mixes.' },
  { id:'carbonic-acid', name:'Carbonic Acid', symbol:'Cb', category:'acid', core:false,
    formula:'H2CO3', molarMass:'62.03 g/mol',
    action:'Forms when CO2 dissolves in water, adding a faint acidity alongside the fizz.',
    uses:'Part of what makes sparkling water taste subtly sharper than still water.' },
  { id:'gluconic-acid', name:'Gluconic Acid', symbol:'Gn', category:'acid', core:false,
    formula:'C6H12O7', molarMass:'196.16 g/mol',
    action:'A mild acid produced by oxidizing glucose, often used as its slow-release lactone form.',
    uses:'Used in reverse-spherification baths as a gentle setting agent.' },

  // ============ SALT (10: 3 core + 7 extended) ============
  { id:'sodium-chloride', name:'Sodium Chloride', symbol:'Nc', category:'salt', core:true,
    formula:'NaCl', molarMass:'58.44 g/mol',
    action:'Draws water out of cells by osmosis and disrupts microbial cell walls.',
    uses:'The oldest and most universal food preservative and seasoning.' },
  { id:'potassium-chloride', name:'Potassium Chloride', symbol:'Pc', category:'salt', core:true,
    formula:'KCl', molarMass:'74.55 g/mol',
    action:'Tastes salty like sodium chloride but with a mild bitter, metallic edge.',
    uses:'Used in reduced-sodium salt blends.' },
  { id:'calcium-chloride', name:'Calcium Chloride', symbol:'Cc', category:'salt', core:true,
    formula:'CaCl2', molarMass:'110.98 g/mol',
    action:'Releases calcium ions that firm pectin and cross-link alginate gels almost instantly.',
    uses:'The setting bath ingredient behind classic spherification.' },
  { id:'sodium-bicarbonate', name:'Sodium Bicarbonate', symbol:'Sb', category:'salt', core:false,
    formula:'NaHCO3', molarMass:'84.01 g/mol',
    action:'Releases CO2 when it meets an acid or enough heat, lifting batters as it does.',
    uses:'Common baking soda \u2014 also used to tenderize meat and darken pretzel crust.' },
  { id:'potassium-bicarbonate', name:'Potassium Bicarbonate', symbol:'Pb', category:'salt', core:false,
    formula:'KHCO3', molarMass:'100.12 g/mol',
    action:'Functions like sodium bicarbonate but contributes potassium instead of sodium.',
    uses:'A low-sodium leavening substitute in some baked goods.' },
  { id:'magnesium-chloride', name:'Magnesium Chloride', symbol:'Mn', category:'salt', core:false,
    formula:'MgCl2', molarMass:'95.21 g/mol',
    action:'Coagulates soy protein by neutralizing the charges keeping it suspended in liquid.',
    uses:'Known as nigari \u2014 the traditional coagulant for making tofu.' },
  { id:'calcium-carbonate', name:'Calcium Carbonate', symbol:'Cr', category:'salt', core:false,
    formula:'CaCO3', molarMass:'100.09 g/mol',
    action:'A mild alkaline mineral that can neutralize acidity and firm plant tissue.',
    uses:'Used to keep pickled vegetables crisp and to fortify calcium-added foods.' },
  { id:'sodium-nitrate', name:'Sodium Nitrate', symbol:'Sn', category:'salt', core:false,
    formula:'NaNO3', molarMass:'84.99 g/mol',
    action:'Slowly converts to nitrite over time, giving long-cured meats sustained protection.',
    uses:'Used in dry-cured salami and other long-aged charcuterie.' },
  { id:'potassium-nitrate', name:'Potassium Nitrate', symbol:'Pn', category:'salt', core:false,
    formula:'KNO3', molarMass:'101.10 g/mol',
    action:'Historically called saltpeter; slowly breaks down to nitrite during curing.',
    uses:'One of the earliest curing salts used to preserve and pink-cure meat.' },
  { id:'ammonium-chloride', name:'Ammonium Chloride', symbol:'Nh', category:'salt', core:false,
    formula:'NH4Cl', molarMass:'53.49 g/mol',
    action:'A mild acidic salt that reacts with baking soda to boost browning and crispness.',
    uses:'Known as salmiak salt \u2014 used in Scandinavian licorice and some flatbreads.' },

  // ============ SUGAR (12: 3 core + 9 extended) ============
  { id:'sucrose', name:'Sucrose', symbol:'Sc', category:'sugar', core:true,
    formula:'C12H22O11', molarMass:'342.30 g/mol',
    action:'A glucose-fructose pair that caramelizes around 160\u00b0C and binds water tightly.',
    uses:'Table sugar \u2014 the baseline sweetener and preservative across nearly every cuisine.' },
  { id:'fructose', name:'Fructose', symbol:'Fr', category:'sugar', core:true,
    formula:'C6H12O6', molarMass:'180.16 g/mol',
    action:'The sweetest common sugar, and highly reactive in browning reactions.',
    uses:'Concentrated in ripe fruit and honey; drives fast caramelization at lower temperatures.' },
  { id:'glucose', name:'Glucose', symbol:'Gu', category:'sugar', core:true,
    formula:'C6H12O6', molarMass:'180.16 g/mol',
    action:'The primary fuel sugar for yeast fermentation and a key Maillard reactant.',
    uses:'Also called dextrose \u2014 used in candy-making to control crystallization.' },
  { id:'lactose', name:'Lactose', symbol:'Lc', category:'sugar', core:false,
    formula:'C12H22O11', molarMass:'342.30 g/mol',
    action:'A glucose-galactose pair that browns unusually fast, even at baking temperatures.',
    uses:'Milk\u2019s natural sugar \u2014 responsible for deep browning in dairy-enriched baked goods.' },
  { id:'maltose', name:'Maltose', symbol:'Mt', category:'sugar', core:false,
    formula:'C12H22O11', molarMass:'342.30 g/mol',
    action:'Two linked glucose units, released when amylase breaks starch apart.',
    uses:'The primary fermentable sugar in malted barley used for beer and whisky.' },
  { id:'galactose', name:'Galactose', symbol:'Ga', category:'sugar', core:false,
    formula:'C6H12O6', molarMass:'180.16 g/mol',
    action:'Half of the lactose molecule, released once lactase splits it apart.',
    uses:'Contributes subtle sweetness in aged, low-lactose cheeses.' },
  { id:'ribose', name:'Ribose', symbol:'Ri', category:'sugar', core:false,
    formula:'C5H10O5', molarMass:'150.13 g/mol',
    action:'A five-carbon sugar released as meat and yeast extracts break down, feeding Maillard browning.',
    uses:'Contributes to the deep savoriness of aged meat and stock reductions.' },
  { id:'xylitol', name:'Xylitol', symbol:'Xy', category:'sugar', core:false,
    formula:'C5H12O5', molarMass:'152.15 g/mol',
    action:'A sugar alcohol that tastes sweet but resists fermentation by most oral bacteria.',
    uses:'A common sugar substitute in "sugar-free" gum and candy.' },
  { id:'sorbitol', name:'Sorbitol', symbol:'So', category:'sugar', core:false,
    formula:'C6H14O6', molarMass:'182.17 g/mol',
    action:'A sugar alcohol that holds moisture well without contributing much sweetness.',
    uses:'Keeps commercial baked goods and dried fruit soft over long storage.' },
  { id:'mannitol', name:'Mannitol', symbol:'M2', category:'sugar', core:false,
    formula:'C6H14O6', molarMass:'182.17 g/mol',
    action:'A sugar alcohol that crystallizes into a fine white powder as it dries.',
    uses:'The white bloom sometimes seen on dried mushrooms and some dried fruits.' },
  { id:'trehalose', name:'Trehalose', symbol:'Tr', category:'sugar', core:false,
    formula:'C12H22O11', molarMass:'342.30 g/mol',
    action:'Stabilizes proteins and cell membranes during freezing and drying.',
    uses:'Helps freeze-dried foods and mushrooms rehydrate closer to their original texture.' },
  { id:'invert-sugar', name:'Invert Sugar', symbol:'Iv', category:'sugar', core:false,
    formula:'Glucose + Fructose (split)', molarMass:'180.16 g/mol (mixture)',
    action:'Sucrose split into its two component sugars, which resist crystallizing back together.',
    uses:'Keeps fondant, syrups, and ice cream smooth rather than gritty.' },

  // ============ HYDROCOLLOID (12: 4 core + 8 extended) ============
  { id:'sodium-alginate', name:'Sodium Alginate', symbol:'Sa', category:'hydrocolloid', core:true,
    formula:'(C6H7NaO6)n', molarMass:'~198 g/mol / unit (polymer)',
    action:'Instantly cross-links into a gel skin on contact with calcium ions.',
    uses:'The core ingredient in both classic and reverse spherification.' },
  { id:'agar-agar', name:'Agar-Agar', symbol:'Aa', category:'hydrocolloid', core:true,
    formula:'Polysaccharide (galactose-based)', molarMass:'Variable (polymer)',
    action:'Melts near 85\u00b0C but doesn\u2019t re-melt until re-heated past that point \u2014 a wide "hysteresis" gap.',
    uses:'Produces firm, sliceable gels that hold their shape even when warm.' },
  { id:'xanthan-gum', name:'Xanthan Gum', symbol:'Xa', category:'hydrocolloid', core:true,
    formula:'Polysaccharide (fermentation-derived)', molarMass:'Variable (high MW polymer)',
    action:'Thickens dramatically at tiny concentrations without needing heat to activate.',
    uses:'Stabilizes gluten-free doughs and keeps salad dressings from separating.' },
  { id:'gelatin', name:'Gelatin', symbol:'Ge', category:'hydrocolloid', core:true,
    formula:'Hydrolyzed collagen', molarMass:'Variable (polypeptide fragments)',
    action:'Melts near body temperature, which is exactly why gelatin desserts "melt in the mouth."',
    uses:'The classic gelling agent in panna cotta, marshmallow, and fruit gummies.' },
  { id:'carrageenan', name:'Carrageenan', symbol:'C2', category:'hydrocolloid', core:false,
    formula:'Sulfated polysaccharide', molarMass:'Variable (polymer)',
    action:'Binds strongly with milk proteins, gelling dairy far more efficiently than plant liquids.',
    uses:'Keeps chocolate milk and some ice creams from separating on the shelf.' },
  { id:'guar-gum', name:'Guar Gum', symbol:'Gg', category:'hydrocolloid', core:false,
    formula:'Galactomannan polysaccharide', molarMass:'Variable (polymer)',
    action:'Hydrates in cold liquid and thickens without ever needing to be heated.',
    uses:'A common thickener in gluten-free baking and no-churn ice cream.' },
  { id:'locust-bean-gum', name:'Locust Bean Gum', symbol:'Lb', category:'hydrocolloid', core:false,
    formula:'Galactomannan polysaccharide', molarMass:'Variable (polymer)',
    action:'Works synergistically with other gums, boosting gel strength beyond what either manages alone.',
    uses:'Paired with carrageenan or xanthan for a more elastic ice-cream texture.' },
  { id:'pectin', name:'Pectin', symbol:'Pe', category:'hydrocolloid', core:false,
    formula:'Polygalacturonic acid', molarMass:'~194 g/mol / unit (polymer)',
    action:'Sets into a gel when sugar and acid pull water away from its dissolved chains.',
    uses:'The natural gelling agent in fruit already present in jams and marmalades.' },
  { id:'gellan-gum', name:'Gellan Gum', symbol:'Gm', category:'hydrocolloid', core:false,
    formula:'Polysaccharide (fermentation-derived)', molarMass:'Variable (polymer)',
    action:'Sets into brittle, ultra-clear gels that hold sharp shapes when cut.',
    uses:'Used for thin, glass-like gel sheets and edible "stained glass" garnishes.' },
  { id:'methylcellulose', name:'Methylcellulose', symbol:'Me', category:'hydrocolloid', core:false,
    formula:'Modified cellulose', molarMass:'Variable (polymer)',
    action:'Gels on heating and turns liquid again on cooling \u2014 the reverse of gelatin.',
    uses:'Lets "hot ice cream" and self-supporting hot foams hold their shape only while warm.' },
  { id:'konjac-glucomannan', name:'Konjac Glucomannan', symbol:'Kg', category:'hydrocolloid', core:false,
    formula:'Glucomannan polysaccharide', molarMass:'Variable (polymer)',
    action:'Forms an unusually strong, chewy, heat-stable gel once set with an alkaline coagulant.',
    uses:'The base of konjac noodles (shirataki) and QQ-textured jellies.' },
  { id:'carboxymethyl-cellulose', name:'Carboxymethyl Cellulose', symbol:'Cx', category:'hydrocolloid', core:false,
    formula:'Modified cellulose', molarMass:'Variable (polymer)',
    action:'Holds water tightly and resists syneresis (weeping) even after freezing and thawing.',
    uses:'Keeps commercial ice cream and gluten-free bread from drying out in the freezer.' },

  // ============ ENZYME (11: 4 core + 7 extended) ============
  { id:'amylase', name:'Amylase', symbol:'Y1', category:'enzyme', core:true,
    formula:'Enzyme (glycoside hydrolase)', molarMass:'~55,000 g/mol',
    action:'Cleaves starch chains into sugars, most active in the 60\u201370\u00b0C range.',
    uses:'Converts malted grain starch into fermentable sugar for beer and whisky.' },
  { id:'pepsin', name:'Pepsin', symbol:'Y2', category:'enzyme', core:true,
    formula:'Enzyme (protease)', molarMass:'~35,000 g/mol',
    action:'A highly acid-tolerant enzyme that begins breaking proteins apart in the stomach.',
    uses:'Historically used, alongside rennet, in some traditional cheese-making processes.' },
  { id:'papain', name:'Papain', symbol:'Y3', category:'enzyme', core:true,
    formula:'Enzyme (cysteine protease)', molarMass:'~23,000 g/mol',
    action:'Cleaves tough muscle proteins apart, softening texture well before heat is applied.',
    uses:'Extracted from papaya and used in commercial meat tenderizers.' },
  { id:'rennet', name:'Rennet (Chymosin)', symbol:'Y4', category:'enzyme', core:true,
    formula:'Enzyme (aspartic protease)', molarMass:'~36,000 g/mol',
    action:'Snips a single stabilizing piece off casein, causing milk proteins to clump into curds.',
    uses:'The traditional coagulant for nearly all rennet-set cheeses.' },
  { id:'bromelain', name:'Bromelain', symbol:'Y5', category:'enzyme', core:false,
    formula:'Enzyme (cysteine protease)', molarMass:'~28,000 g/mol',
    action:'Breaks down gelatin so aggressively that fresh pineapple stops gelatin desserts from setting.',
    uses:'Used as a natural meat tenderizer, extracted from fresh pineapple stems.' },
  { id:'lipase', name:'Lipase', symbol:'Y6', category:'enzyme', core:false,
    formula:'Enzyme (esterase)', molarMass:'~50,000 g/mol',
    action:'Breaks triglycerides into free fatty acids, contributing sharp, "aged" flavors.',
    uses:'Deliberately added to some Italian cheeses for a distinctive piccante bite.' },
  { id:'lactase', name:'Lactase', symbol:'Y7', category:'enzyme', core:false,
    formula:'Enzyme (glycoside hydrolase)', molarMass:'~120,000 g/mol',
    action:'Splits lactose into glucose and galactose, both of which taste sweeter than lactose itself.',
    uses:'Used to make lactose-free milk taste naturally sweeter than regular milk.' },
  { id:'invertase', name:'Invertase', symbol:'Y8', category:'enzyme', core:false,
    formula:'Enzyme (glycoside hydrolase)', molarMass:'~135,000 g/mol',
    action:'Splits sucrose into glucose and fructose, which resist re-crystallizing.',
    uses:'Turns firm sugar fondant centers into liquid over a few days in filled chocolates.' },
  { id:'trypsin', name:'Trypsin', symbol:'Y9', category:'enzyme', core:false,
    formula:'Enzyme (serine protease)', molarMass:'~23,300 g/mol',
    action:'A digestive protease that continues breaking proteins down after pepsin has started the job.',
    uses:'Relevant in fermented fish and meat products where gut enzymes drive early breakdown.' },
  { id:'protease-general', name:'Protease (general)', symbol:'Y10', category:'enzyme', core:false,
    formula:'Enzyme class (hydrolase)', molarMass:'Variable',
    action:'Any enzyme that cuts proteins into shorter peptides and free amino acids.',
    uses:'The broad enzyme family behind meat tenderizing and savory fermented pastes.' },
  { id:'pectinase', name:'Pectinase', symbol:'Y11', category:'enzyme', core:false,
    formula:'Enzyme (glycoside hydrolase)', molarMass:'~44,000 g/mol',
    action:'Breaks down pectin in plant cell walls, thinning and clarifying fruit liquid.',
    uses:'Used commercially to clarify apple juice and improve wine-press yield.' },

  // ============ FLAVOR COMPOUND (13: 4 core + 9 extended) ============
  { id:'capsaicin', name:'Capsaicin', symbol:'Cp', category:'flavor', core:true,
    formula:'C18H27NO3', molarMass:'305.41 g/mol',
    action:'Binds the same heat-sensing receptor the body uses for real thermal pain.',
    uses:'The compound responsible for all chili heat, measured on the Scoville scale.' },
  { id:'vanillin', name:'Vanillin', symbol:'Va', category:'flavor', core:true,
    formula:'C8H8O3', molarMass:'152.15 g/mol',
    action:'The single dominant aroma molecule in cured vanilla pods, easily synthesized artificially.',
    uses:'The world\u2019s most widely used flavor compound, natural or synthetic.' },
  { id:'piperine', name:'Piperine', symbol:'Pi', category:'flavor', core:true,
    formula:'C17H19NO3', molarMass:'285.34 g/mol',
    action:'A milder heat-receptor activator than capsaicin, giving a sharper, more fleeting bite.',
    uses:'The pungent compound in black pepper \u2014 valuable enough to once fund empires.' },
  { id:'glutamate', name:'Monosodium Glutamate', symbol:'Gt', category:'flavor', core:true,
    formula:'C5H8NNaO4', molarMass:'169.11 g/mol',
    action:'Binds dedicated umami receptors on the tongue, distinct from the four classic tastes.',
    uses:'Occurs naturally in aged cheese, tomatoes, and cured fish; isolated in 1908 from kombu.' },
  { id:'allicin', name:'Allicin', symbol:'Al2', category:'flavor', core:false,
    formula:'C6H10OS2', molarMass:'162.27 g/mol',
    action:'Forms only after cell damage triggers a reaction between two separate stored compounds.',
    uses:'Explains why crushed garlic smells sharper and faster than a whole, uncut clove.' },
  { id:'cinnamaldehyde', name:'Cinnamaldehyde', symbol:'Cd', category:'flavor', core:false,
    formula:'C9H8O', molarMass:'132.16 g/mol',
    action:'A fat- and alcohol-soluble aromatic that extracts poorly into plain water.',
    uses:'The primary aroma compound in cinnamon bark.' },
  { id:'eugenol', name:'Eugenol', symbol:'Eg', category:'flavor', core:false,
    formula:'C10H12O2', molarMass:'164.20 g/mol',
    action:'A warm, slightly numbing aromatic compound, mildly anesthetic in concentrated form.',
    uses:'The dominant note in clove, historically prized on medieval spice routes.' },
  { id:'limonene', name:'Limonene', symbol:'Lm', category:'flavor', core:false,
    formula:'C10H16', molarMass:'136.23 g/mol',
    action:'A volatile aromatic oil concentrated in citrus rind rather than the flesh.',
    uses:'What you smell first when zesting an orange or lemon.' },
  { id:'menthol', name:'Menthol', symbol:'Mh', category:'flavor', core:false,
    formula:'C10H20O', molarMass:'156.27 g/mol',
    action:'Triggers cold-sensing receptors directly, producing a cooling sensation without any temperature change.',
    uses:'Gives mint its signature "cool" bite in both food and confectionery.' },
  { id:'diacetyl', name:'Diacetyl', symbol:'Dt', category:'flavor', core:false,
    formula:'C4H6O2', molarMass:'86.09 g/mol',
    action:'A byproduct of fermentation with an intensely buttery aroma even in trace amounts.',
    uses:'Deliberately encouraged in some beer styles and cultured butter for a rounder flavor.' },
  { id:'thymol', name:'Thymol', symbol:'Tm2', category:'flavor', core:false,
    formula:'C10H14O', molarMass:'150.22 g/mol',
    action:'A phenolic compound with mild antimicrobial properties alongside its herbal aroma.',
    uses:'The primary aromatic compound in thyme and some oregano varieties.' },
  { id:'carvone', name:'Carvone', symbol:'Cv', category:'flavor', core:false,
    formula:'C10H14O', molarMass:'150.22 g/mol',
    action:'The same formula in two mirror-image forms smells like caraway in one and spearmint in the other.',
    uses:'A textbook example of how molecular shape alone determines aroma.' },
  { id:'anethole', name:'Anethole', symbol:'An', category:'flavor', core:false,
    formula:'C10H12O', molarMass:'148.20 g/mol',
    action:'A sweet, licorice-like aromatic compound found across several unrelated plant families.',
    uses:'Shared by fennel, anise, and star anise despite the plants being botanically distant.' },

  // ============ PRESERVATIVE (11: 3 core + 8 extended) ============
  { id:'sodium-benzoate', name:'Sodium Benzoate', symbol:'Nb', category:'preservative', core:true,
    formula:'C7H5NaO2', molarMass:'144.10 g/mol',
    action:'Most effective in acidic foods, where it disrupts microbial cell metabolism.',
    uses:'A common preservative in acidic condiments, sodas, and fruit juices.' },
  { id:'sodium-nitrite', name:'Sodium Nitrite', symbol:'Nt', category:'preservative', core:true,
    formula:'NaNO2', molarMass:'69.00 g/mol',
    action:'Blocks the growth of botulism-causing bacteria and locks in a stable pink color.',
    uses:'The curing salt behind bacon, ham, and hot dogs\u2019 characteristic color and safety.' },
  { id:'sulfur-dioxide', name:'Sulfur Dioxide', symbol:'Sd', category:'preservative', core:true,
    formula:'SO2', molarMass:'64.07 g/mol',
    action:'Inhibits both microbial growth and enzymatic browning at very low concentrations.',
    uses:'Used in winemaking and dried fruit to prevent spoilage and preserve color.' },
  { id:'potassium-sorbate', name:'Potassium Sorbate', symbol:'Ks', category:'preservative', core:false,
    formula:'C6H7KO2', molarMass:'150.22 g/mol',
    action:'Specifically targets mold and yeast growth without much effect on bacteria.',
    uses:'Common in cheese rinds, wine, and baked goods to extend shelf life.' },
  { id:'calcium-propionate', name:'Calcium Propionate', symbol:'Cp2', category:'preservative', core:false,
    formula:'C6H10CaO4', molarMass:'186.22 g/mol',
    action:'Inhibits mold and some bacteria without interfering with yeast fermentation.',
    uses:'Added to commercial bread dough to delay mold growth after baking.' },
  { id:'bha', name:'BHA', symbol:'Bh', category:'preservative', core:false,
    formula:'C11H16O2', molarMass:'180.24 g/mol',
    action:'A synthetic antioxidant that intercepts the chain reaction of fat oxidation.',
    uses:'Slows rancidity development in packaged snack foods and cereals.' },
  { id:'bht', name:'BHT', symbol:'Bo', category:'preservative', core:false,
    formula:'C15H24O', molarMass:'220.35 g/mol',
    action:'Works alongside BHA as a fat-soluble antioxidant, often used in combination.',
    uses:'Found in packaging and some cereals to extend fat freshness.' },
  { id:'edta', name:'EDTA', symbol:'Ed', category:'preservative', core:false,
    formula:'C10H16N2O8', molarMass:'292.24 g/mol',
    action:'Binds trace metal ions that would otherwise catalyze oxidation and discoloration.',
    uses:'Used in canned goods and dressings to preserve color and stabilize flavor.' },
  { id:'nisin', name:'Nisin', symbol:'Nn', category:'preservative', core:false,
    formula:'Peptide (34 amino acids)', molarMass:'~3,350 g/mol',
    action:'A naturally produced antimicrobial peptide effective against many food-spoilage bacteria.',
    uses:'Used in some cheeses and canned foods as a natural preservative.' },
  { id:'sodium-metabisulfite', name:'Sodium Metabisulfite', symbol:'Sm', category:'preservative', core:false,
    formula:'Na2S2O5', molarMass:'190.10 g/mol',
    action:'Releases sulfur dioxide gradually, extending its antimicrobial and antioxidant effect.',
    uses:'Used in home winemaking and cider-making to sanitize and stabilize.' },
  { id:'erythorbic-acid', name:'Erythorbic Acid', symbol:'Ey', category:'preservative', core:false,
    formula:'C6H8O6', molarMass:'176.12 g/mol',
    action:'A mirror-image isomer of vitamin C with similar antioxidant power but no nutritional value.',
    uses:'Speeds up curing and stabilizes color in processed meats.' },
];
