/* ================= RECIPE VAULT DATA =================
   54 recipes total across 5 eras (11+11+11+11+10).
   Each recipe carries its method steps (used for cooking-mode
   checkboxes) plus a chemical-analysis drawer explaining the
   food science behind the technique.
   ======================================================== */

const ERA_META = {
  neolithic:  { label:'Neolithic',    years:'10,000–4,000 BCE', color:'#B5583A' },
  ancient:    { label:'Ancient Civ.', years:'4,000 BCE–500 CE', color:'#C97A2E' },
  medieval:   { label:'Medieval',     years:'500–1,500 CE',     color:'#6B4E71' },
  industrial: { label:'Industrial',   years:'1760–1900',        color:'#4C6B58' },
  modern:     { label:'Molecular',    years:'1950–Present',     color:'#2FE6C9' },
};

const RECIPES = [
  // ==================== NEOLITHIC (11) ====================
  { id:'fire-roasted-boar', title:'Fire-Roasted Wild Boar', era:'neolithic', difficulty:'Medium', time:'2 hr',
    tagline:'Whole-fire roasting over an open flame, the oldest cooking method there is.',
    scienceTip:'The Maillard Reaction',
    steps:['Skewer a boar leg or shoulder on a green-wood spit.','Build a bed of hardwood coals and position the meat 30cm above them.','Rotate slowly and continuously for 90–120 minutes, basting with rendered fat.','Rest for 15 minutes before carving.'],
    science:'Direct heat above 140°C drives the Maillard reaction between surface proteins and sugars, producing the deep brown crust and hundreds of new roasted-meat aroma compounds no raw fire could otherwise create.' },
  { id:'emmer-flatbread', title:'Emmer Flatbread', era:'neolithic', difficulty:'Easy', time:'25 min',
    tagline:'Ground emmer wheat, water, and fire — one of the first processed foods.',
    scienceTip:'Gluten Development',
    steps:['Grind whole emmer berries into a coarse flour using a mortar or grain mill.','Mix with water and a pinch of salt into a stiff, workable dough.','Knead briefly and press into thin rounds by hand.','Cook on a hot flat stone or dry skillet, 2–3 minutes per side.'],
    science:'Emmer\u2019s weaker gluten forms a looser network than modern wheat, which is exactly why ancient flatbreads come out denser and flatter rather than airy — there simply isn\u2019t enough elastic structure to trap much gas.' },
  { id:'acorn-leaching-porridge', title:'Acorn Leaching Porridge', era:'neolithic', difficulty:'Medium', time:'2 days (mostly soaking)',
    tagline:'Bitter acorns made edible by patiently washing the tannins out.',
    scienceTip:'Osmotic Diffusion',
    steps:['Shell and coarsely crush dried acorns.','Submerge the crushed acorns in successive changes of fresh water over 24–48 hours.','Taste periodically until the bitterness fades.','Simmer the leached acorn meal in water until it thickens into a porridge.'],
    science:'Tannins are water-soluble, so repeatedly replacing the soaking water lets them diffuse out of the acorn meal by simple concentration gradient — no cooking required, just patient osmosis.' },
  { id:'wild-grain-porridge', title:'Wild Grain Porridge', era:'neolithic', difficulty:'Easy', time:'30 min',
    tagline:'Simmered grain was easier on teeth than raw kernels — and stretched further.',
    scienceTip:'Starch Gelatinization',
    steps:['Crack wild barley or oat grains coarsely.','Simmer in water, roughly 1 part grain to 3 parts water, for 20–25 minutes.','Stir occasionally as it thickens.','Sweeten with wild honey or foraged berries if available.'],
    science:'Heat forces water into starch granules until they swell and rupture — gelatinization — turning hard grain and water into something spoonable and far easier to digest than the raw kernel.' },
  { id:'foraged-berry-preserve', title:'Foraged Berry Preserve', era:'neolithic', difficulty:'Easy', time:'40 min',
    tagline:'Wild berries concentrated with honey into something that outlasts the season.',
    scienceTip:'Sugar as Preservative',
    steps:['Simmer foraged berries with a generous measure of wild honey.','Mash gently as the mixture reduces.','Continue simmering until thick enough to coat a spoon.','Store in a sealed clay vessel in a cool, dark place.'],
    science:'Concentrated sugar binds water so tightly that spoilage microbes are left without enough free moisture to grow — the same principle behind every jam made since.' },
  { id:'smoked-river-fish', title:'Smoked River Fish', era:'neolithic', difficulty:'Medium', time:'6 hr',
    tagline:'Slow smoke over a low fire turned a day\u2019s catch into weeks of food.',
    scienceTip:'Phenolic Preservation',
    steps:['Split and clean freshwater fish, leaving skin on.','Rub lightly with foraged salt if available.','Hang over a smoldering, low hardwood fire for 4–6 hours.','Store in a dry, ventilated space.'],
    science:'Wood smoke deposits phenolic compounds onto the fish\u2019s surface, which both slow bacterial growth and antioxidize surface fat — smoking is dehydration and light chemical preservation happening at once.' },
  { id:'nettle-greens-stew', title:'Nettle & Wild Greens Stew', era:'neolithic', difficulty:'Easy', time:'35 min',
    tagline:'Blanching neutralized the sting and unlocked greens too painful to eat raw.',
    scienceTip:'Thermal Deactivation',
    steps:['Gather young nettle leaves and other wild greens using gloves.','Blanch briefly in boiling water to neutralize the sting.','Chop and simmer with water and any available roots for 20 minutes.','Season with foraged salt or herbs.'],
    science:'Nettle\u2019s sting comes from tiny needle-like structures injecting irritants on contact; heat above roughly 60°C denatures the responsible proteins, permanently disarming them before the leaf ever reaches the pot.' },
  { id:'einkorn-griddle-cakes', title:'Cracked Einkorn Griddle Cakes', era:'neolithic', difficulty:'Easy', time:'20 min',
    tagline:'Coarsely cracked grain griddled directly on a hot stone.',
    scienceTip:'Surface Browning',
    steps:['Crack einkorn berries coarsely with a grinding stone.','Mix with water into a thick, pourable batter.','Ladle onto a very hot flat stone.','Cook 3–4 minutes per side until the surface browns and crisps.'],
    science:'The coarse cracked grain leaves more exposed starch and protein at the surface than fine flour would, giving a rougher, more textured crust as Maillard browning takes hold unevenly across each fragment.' },
  { id:'pit-roasted-roots', title:'Pit-Roasted Root Vegetables', era:'neolithic', difficulty:'Medium', time:'4 hr',
    tagline:'Buried beneath hot coals, roots caramelized slowly with almost no attention needed.',
    scienceTip:'Caramelization',
    steps:['Dig a shallow pit and line it with hot coals.','Wrap wild roots and tubers in large leaves.','Bury the bundle under the coals and cover with earth.','Leave to cook for 3–4 hours, then unearth and unwrap.'],
    science:'The slow, even heat of buried coals stays just hot enough to caramelize the natural sugars in root vegetables without scorching the surface — a gentler, more forgiving heat than an open flame.' },
  { id:'wild-honey-mead', title:'Wild Honey Mead', era:'neolithic', difficulty:'Medium', time:'3–6 weeks',
    tagline:'Diluted wild honey left to ferment into humanity\u2019s likely first alcoholic drink.',
    scienceTip:'Wild Yeast Fermentation',
    steps:['Dilute wild honey with water, roughly 1 part honey to 4 parts water.','Leave uncovered briefly to pick up airborne wild yeast.','Cover loosely and let ferment in a cool, dark place for 3–6 weeks.','Strain before drinking.'],
    science:'Wild yeasts naturally present on honeycomb and in the air consume the honey\u2019s sugars and produce ethanol and CO2 as byproducts — fermentation that requires no added culture at all.' },
  { id:'charred-grain-gruel', title:'Charred Grain Gruel', era:'neolithic', difficulty:'Easy', time:'25 min',
    tagline:'Lightly toasting grain before boiling deepened its flavor considerably.',
    scienceTip:'Dry-Heat Browning',
    steps:['Toast whole grains in a dry, hot clay vessel until lightly charred.','Crush the toasted grains coarsely.','Simmer in water for 15–20 minutes until thickened.','Serve warm.'],
    science:'Toasting before boiling triggers Maillard browning on the dry grain surface first — a step plain boiling skips entirely, which is why toasted-grain gruels taste noticeably deeper than untoasted ones.' },

  // ==================== ANCIENT CIVILIZATIONS (11) ====================
  { id:'roman-garum', title:'Roman Garum', era:'ancient', difficulty:'Advanced', time:'4–6 weeks',
    tagline:'Fermented fish sauce that flavored nearly everything in the Roman kitchen.',
    scienceTip:'Enzymatic Autolysis',
    steps:['Layer small whole fish with coarse salt in a sealed vessel, roughly 1 part salt to 5 parts fish.','Leave in a warm, sunlit spot, stirring every few days.','Ferment for 4–6 weeks as the fish breaks down into a strong liquid.','Strain through cloth; discard the solids.'],
    science:'Salt draws out water and slows spoilage bacteria while the fish\u2019s own digestive enzymes keep working, breaking proteins into free amino acids — including glutamate, the source of garum\u2019s intense umami.' },
  { id:'egyptian-yeast-bread', title:'Egyptian Yeast Bread', era:'ancient', difficulty:'Medium', time:'4 hr',
    tagline:'The first leavened loaves, likely discovered by accident from airborne wild yeast.',
    scienceTip:'CO2 Gas Trapping',
    steps:['Mix flour, water, and a portion of yesterday\u2019s fermented dough as starter.','Knead until smooth and elastic.','Let rise in a warm spot for 2–3 hours until doubled.','Bake in a clay oven until deeply golden.'],
    science:'Wild yeast consumes sugars in the dough and releases CO2, which gluten\u2019s elastic network traps as thousands of tiny bubbles — the structural reason leavened bread rises and holds an open crumb.' },
  { id:'osmotic-cured-olives', title:'Osmotic Salt-Cured Olives', era:'ancient', difficulty:'Medium', time:'4–6 weeks',
    tagline:'Bitter raw olives made edible purely through salt and patience.',
    scienceTip:'Osmotic Preservation',
    steps:['Crack fresh olives lightly to help brine penetrate.','Submerge in a strong salt brine.','Change the brine weekly for 4–6 weeks.','Finish in olive oil with herbs.'],
    science:'Salt draws bitter oleuropein out of the olive flesh by osmosis while simultaneously making the brine inhospitable to spoilage bacteria — curing and preservation happening through the same mechanism.' },
  { id:'ancient-honey-cake', title:'Ancient Honey Cake', era:'ancient', difficulty:'Medium', time:'50 min',
    tagline:'A dense, honey-soaked cake offered in Egyptian and Greek households alike.',
    scienceTip:'Sugar as Preservative',
    steps:['Mix ground barley flour, crushed dates, and a generous measure of honey into a thick batter.','Fold in chopped nuts and a pinch of salt.','Bake in a covered clay dish over low coals for about 35 minutes.','Soak the warm cake in extra honey before serving.'],
    science:'Honey is roughly 80% sugar, which binds water tightly enough to starve mold and bacteria of the moisture they need — the same reason honey-soaked cakes kept for weeks without spoiling.' },
  { id:'mesopotamian-beer', title:'Mesopotamian Beer', era:'ancient', difficulty:'Advanced', time:'1–2 weeks',
    tagline:'Barley bread, crumbled and fermented, in one of the oldest known recipes.',
    scienceTip:'Saccharification',
    steps:['Bake a lightly-leavened barley loaf and let it dry out.','Crumble the dried bread into water and let it soak.','Add wild yeast and let ferment in a covered vessel for 5–7 days.','Strain through reed straws to filter out solids while drinking.'],
    science:'Sprouted barley\u2019s natural amylase enzymes had already converted much of its starch into fermentable sugar before baking, so soaking the crumbled bread releases sugar wild yeast can immediately ferment into alcohol.' },
  { id:'greek-olive-oil-pressing', title:'Greek Olive Oil Pressing', era:'ancient', difficulty:'Medium', time:'3 hr',
    tagline:'Crushing and pressing separated liquid gold from solid fruit.',
    scienceTip:'Lipid Extraction',
    steps:['Crush ripe olives into a coarse paste using a stone mill.','Press the paste to separate liquid from solids.','Let the liquid settle so oil rises above the water layer.','Skim off the floating oil.'],
    science:'Olive oil is less dense than the water naturally present in olive flesh, so once cell walls are physically ruptured by crushing, gravity alone is enough to separate the two liquids over time.' },
  { id:'egyptian-salted-fish', title:'Egyptian Salted Fish (Fesikh)', era:'ancient', difficulty:'Advanced', time:'2–3 weeks',
    tagline:'Whole fish buried in salt and left to cure in the desert heat.',
    scienceTip:'Osmotic Dehydration',
    steps:['Clean whole fish, leaving scales intact.','Pack tightly in coarse salt inside a sealed vessel.','Leave to cure in a warm, dry place for 2–3 weeks.','Rinse lightly before serving.'],
    science:'Salt pulls water out of the fish\u2019s cells faster than any bacteria can multiply, dropping the available moisture below the threshold most spoilage organisms need to survive.' },
  { id:'roman-posca', title:'Roman Posca', era:'ancient', difficulty:'Easy', time:'10 min',
    tagline:'Vinegar and water — the everyday drink of Roman soldiers and laborers.',
    scienceTip:'Acetic Acid Fermentation',
    steps:['Combine soured wine vinegar with water, roughly 1 part vinegar to 4 parts water.','Add a small amount of honey if available.','Stir well.','Serve at room temperature.'],
    science:'The vinegar itself is the product of acetic acid bacteria oxidizing wine\u2019s ethanol into acetic acid — diluting it with water simply tunes an already-fermented product to a drinkable strength.' },
  { id:'chinese-fermented-soy-paste', title:'Chinese Fermented Soybean Paste', era:'ancient', difficulty:'Advanced', time:'2–3 months',
    tagline:'An early jiang — soybeans broken down by mold into a deeply savory paste.',
    scienceTip:'Protease Fermentation',
    steps:['Steam whole soybeans until soft.','Inoculate with a koji mold culture and let it grow for 2–3 days.','Mix with brine and transfer to a fermentation vessel.','Ferment for 2–3 months, stirring occasionally.'],
    science:'Koji mold secretes protease enzymes that break soy protein down into free amino acids, including glutamate — the slow chemical process behind the deep umami of aged soy pastes and sauces.' },
  { id:'indian-ghee-clarification', title:'Indian Ghee Clarification', era:'ancient', difficulty:'Easy', time:'40 min',
    tagline:'Simmering butter until milk solids separate leaves a shelf-stable golden fat.',
    scienceTip:'Casein Separation',
    steps:['Simmer butter over low heat until it foams.','Continue simmering as milk solids sink and brown lightly.','Skim off any foam on the surface.','Strain the golden liquid through cloth, discarding the browned solids.'],
    science:'Butter is an emulsion of fat, water, and milk proteins; gentle heat evaporates the water and lets casein proteins settle and brown, leaving pure, shelf-stable fat behind once strained.' },
  { id:'babylonian-date-syrup', title:'Babylonian Date Syrup', era:'ancient', difficulty:'Easy', time:'1 hr',
    tagline:'Simmered dates reduced into a thick natural sweetener.',
    scienceTip:'Sugar Concentration',
    steps:['Simmer pitted dates in water until very soft.','Mash thoroughly and strain through cloth.','Return the liquid to the pot and simmer until thick.','Cool and store in a sealed vessel.'],
    science:'As water evaporates during simmering, the dates\u2019 natural sugars become increasingly concentrated, both thickening the syrup and pushing its water activity low enough to resist spoilage.' },

  // ==================== MEDIEVAL (11) ====================
  { id:'medieval-spiced-wine', title:'Medieval Spiced Wine', era:'medieval', difficulty:'Easy', time:'20 min',
    tagline:'Hypocras — a warmed wine perfumed with imported spice-route aromatics.',
    scienceTip:'Aromatic Extraction',
    steps:['Combine red wine with cinnamon, clove, and a few threads of saffron in a pot.','Add sugar or honey to taste.','Warm gently over low heat for 10–15 minutes — do not boil.','Strain out the whole spices before serving warm.'],
    science:'Most aromatic spice compounds — cinnamaldehyde, eugenol — are fat- and alcohol-soluble rather than water-soluble, so warm wine pulls far more flavor out of whole spices than water ever could.' },
  { id:'medieval-pottage', title:'Medieval Pottage', era:'medieval', difficulty:'Medium', time:'1 hr 15 min',
    tagline:'A thick vegetable-and-grain stew that simmered over the hearth for days at a time.',
    scienceTip:'Collagen Breakdown',
    steps:['Combine root vegetables, dried peas, and barley in a large pot with water or broth.','Add a well-worked bone or cut of tough meat if available.','Simmer very gently for 60–90 minutes, topping up liquid as needed.','Season with salt and whatever herbs are on hand.'],
    science:'Long, low simmering slowly converts tough collagen in bone and connective tissue into gelatin, which gives an all-day pottage its silky, thickened body without any flour.' },
  { id:'distilled-aqua-vitae', title:'Distilled Aqua Vitae', era:'medieval', difficulty:'Advanced', time:'2 hr',
    tagline:'Alchemists\u2019 "water of life" — wine concentrated by boiling-point separation.',
    scienceTip:'Fractional Distillation',
    steps:['Heat fermented wine gently in a still.','Collect the vapor as it rises through the still\u2019s neck.','Cool and condense the vapor back into liquid.','Discard the first and last fractions, keeping the clean middle run.'],
    science:'Ethanol boils at 78°C, well below water\u2019s 100°C, so gentle heating vaporizes proportionally more alcohol than water — repeating this separation is what let medieval alchemists concentrate wine into spirit.' },
  { id:'herbal-infused-oil', title:'Herbal Infused Oil', era:'medieval', difficulty:'Easy', time:'2 weeks (mostly resting)',
    tagline:'Steeping herbs in fat pulled out flavors water alone couldn\u2019t reach.',
    scienceTip:'Lipid Solubilization',
    steps:['Pack dried herbs loosely into a jar.','Cover completely with olive or another neutral oil.','Seal and let steep in a dark place for 2 weeks, shaking occasionally.','Strain out the solids before use.'],
    science:'Many aromatic and medicinal plant compounds are fat-soluble rather than water-soluble, so oil — not water or vinegar — is what actually pulls them out of the plant material over time.' },
  { id:'salt-cured-ham', title:'Salt-Cured Ham', era:'medieval', difficulty:'Advanced', time:'6–12 months',
    tagline:'A whole leg, buried in salt for months, transformed into something shelf-stable.',
    scienceTip:'Osmotic Curing',
    steps:['Pack a whole ham leg completely in coarse salt.','Leave to cure in a cool space for 2–4 weeks, depending on size.','Rinse off excess salt and hang to dry in a ventilated space.','Age for several months to a year before slicing.'],
    science:'Salt continues drawing moisture out of the meat over weeks, lowering water activity gradually enough that beneficial curing bacteria and enzymes have time to develop flavor before harmful ones can take hold.' },
  { id:'medieval-gingerbread', title:'Spiced Gingerbread (Lebkuchen)', era:'medieval', difficulty:'Medium', time:'1 hr',
    tagline:'A dense, spiced cake built entirely on the newly-arrived luxury of imported spice.',
    scienceTip:'Maillard + Aromatic Compounds',
    steps:['Warm honey gently and stir in ground ginger, cinnamon, and clove.','Fold in flour and any available nuts or dried fruit.','Shape into a flat cake or small rounds.','Bake in a low oven until firm and deeply colored.'],
    science:'Both the Maillard reaction from honey and flour, and the fat-soluble aromatics from ginger and clove, develop together in the oven — one builds the color, the other builds the aroma.' },
  { id:'verjuice', title:'Verjuice', era:'medieval', difficulty:'Easy', time:'15 min',
    tagline:'Pressed unripe grapes provided a milder acid than vinegar for delicate sauces.',
    scienceTip:'Organic Acid Extraction',
    steps:['Press unripe, green grapes to extract their juice.','Strain through cloth to remove pulp and seeds.','Use fresh, or simmer briefly to concentrate.','Store refrigerated or use within a few days.'],
    science:'Unripe grapes are dominated by malic and tartaric acid rather than sugar, giving verjuice a gentler, rounder sourness than vinegar\u2019s sharp acetic acid.' },
  { id:'marzipan', title:'Marzipan', era:'medieval', difficulty:'Medium', time:'30 min',
    tagline:'Ground almonds and sugar, worked into a smooth, moldable paste.',
    scienceTip:'Lipid-Sugar Emulsification',
    steps:['Grind blanched almonds into a fine paste.','Work in powdered sugar gradually.','Add a small amount of rosewater or egg white to bind.','Knead until smooth and shape as desired.'],
    science:'Almonds\u2019 natural oils coat the sugar and ground almond particles, binding them into a cohesive paste — the same fat-based binding logic behind any nut butter.' },
  { id:'medieval-cheese-curds', title:'Medieval Cheese Curds', era:'medieval', difficulty:'Medium', time:'2 hr',
    tagline:'Warm milk, set with rennet, separated into curds and whey.',
    scienceTip:'Enzymatic Coagulation',
    steps:['Warm fresh milk gently to just below simmering.','Stir in a small amount of rennet and let sit undisturbed.','Once firmly set, cut the curd into cubes.','Drain in cloth, pressing gently to remove whey.'],
    science:'Rennet\u2019s enzyme snips a single stabilizing fragment off casein proteins, causing them to clump together into a solid curd network that traps fat and water while whey drains away.' },
  { id:'candied-citrus-peel', title:'Candied Citrus Peel', era:'medieval', difficulty:'Medium', time:'2 hr',
    tagline:'Bitter peel made sweet and shelf-stable through repeated sugar syrup soaking.',
    scienceTip:'Osmotic Sugar Preservation',
    steps:['Simmer citrus peel in water, changing the water twice to reduce bitterness.','Simmer the softened peel in a sugar syrup until translucent.','Remove and let dry on a rack.','Toss in granulated sugar once tacky.'],
    science:'As the peel simmers in syrup, water inside its cells is gradually replaced by concentrated sugar solution, which both sweetens it and preserves it the same way any candied fruit is preserved.' },
  { id:'mulled-cider', title:'Mulled Cider', era:'medieval', difficulty:'Easy', time:'25 min',
    tagline:'Warmed apple cider infused with whole spices for cold hall dinners.',
    scienceTip:'Pectin Release',
    steps:['Warm apple cider gently with cinnamon sticks and cloves.','Simmer for 15–20 minutes without boiling.','Strain out the whole spices.','Serve warm.'],
    science:'Gentle simmering releases a small amount of pectin from residual apple solids into the liquid, giving mulled cider a very slightly thicker mouthfeel than the raw pressed juice.' },

  // ==================== INDUSTRIAL (11) ====================
  { id:'industrial-preserve-jar', title:'Industrial Preserve Jar', era:'industrial', difficulty:'Medium', time:'1 hr 30 min',
    tagline:'Appert\u2019s method — heat-sealed jars that made seasons irrelevant.',
    scienceTip:'Thermal Sterilization',
    steps:['Pack ripe fruit or vegetables tightly into sterilized glass jars.','Fill with hot syrup or brine, leaving a small headspace.','Seal loosely and submerge jars in a boiling water bath for 20–40 minutes.','Tighten seals fully once cooled.'],
    science:'Sustained heat above 100°C destroys the microorganisms and enzymes that cause spoilage, while the sealed jar prevents new contamination — Nicolas Appert\u2019s 1809 method, decades before anyone knew germs were the cause.' },
  { id:'baking-powder-biscuit', title:'Industrial Baking Powder Biscuit', era:'industrial', difficulty:'Easy', time:'25 min',
    tagline:'Chemical leavening replaced hours of yeast fermentation with a single spoonful.',
    scienceTip:'Acid-Base Leavening',
    steps:['Cut cold butter into flour until it resembles coarse crumbs.','Stir in baking powder, salt, and milk until just combined.','Pat into a 2cm-thick round and cut into biscuits.','Bake at 220°C (425°F) for 12–14 minutes until risen and golden.'],
    science:'Baking powder pairs an acid and a base that only react once wet and heated, releasing carbon dioxide bubbles on demand — turning a fermentation that once took hours into a chemical reaction that takes seconds.' },
  { id:'pasteurized-milk', title:'Pasteurized Milk', era:'industrial', difficulty:'Easy', time:'30 min',
    tagline:'Brief, precise heating that made milk safe to transport and store.',
    scienceTip:'Thermal Pathogen Elimination',
    steps:['Heat fresh milk to 63°C (145°F).','Hold at that temperature for 30 minutes, stirring occasionally.','Cool rapidly in an ice bath.','Store refrigerated.'],
    science:'Louis Pasteur\u2019s 1864 method uses heat precisely calibrated to kill common pathogenic bacteria while staying just low enough to avoid cooking the milk\u2019s proteins or noticeably changing its flavor.' },
  { id:'canned-condensed-milk', title:'Canned Condensed Milk', era:'industrial', difficulty:'Medium', time:'1 hr',
    tagline:'Milk reduced and heavily sweetened until it could be sealed in a tin for years.',
    scienceTip:'Maillard + Sugar Concentration',
    steps:['Combine milk with a large amount of sugar.','Simmer gently, stirring often, until reduced by roughly half.','Seal into sterilized cans while hot.','Process cans in a hot water bath.'],
    science:'The combination of high sugar concentration and residual milk proteins drives visible Maillard browning even at relatively low simmering temperatures, giving condensed milk its characteristic caramel-like tint.' },
  { id:'industrial-margarine', title:'Margarine', era:'industrial', difficulty:'Medium', time:'1 hr',
    tagline:'A butter substitute made by hardening liquid vegetable oil.',
    scienceTip:'Fat Hydrogenation',
    steps:['Heat vegetable oil with an emulsifier and water.','Introduce hydrogen gas under pressure with a catalyst to partially harden the fat.','Blend until a stable, spreadable emulsion forms.','Chill until firm.'],
    science:'Hydrogenation adds hydrogen atoms across some of the oil\u2019s double bonds, straightening the fat molecules so they pack more like a saturated fat — raising the melting point from liquid to spreadable solid.' },
  { id:'powdered-gelatin-dessert', title:'Powdered Gelatin Dessert', era:'industrial', difficulty:'Easy', time:'20 min + chill',
    tagline:'Industrially extracted collagen turned into a convenient jiggling dessert.',
    scienceTip:'Collagen Hydrolysis',
    steps:['Dissolve powdered gelatin in hot water or juice.','Stir until fully dissolved with no visible grains.','Pour into molds.','Chill for at least 4 hours until fully set.'],
    science:'Industrial processing hydrolyzes collagen into shorter, water-soluble fragments that dissolve on heating and re-link into a wobbly gel network on cooling — the same chemistry as slow-cooked collagen, just pre-processed.' },
  { id:'commercial-yeast-bread', title:'Commercial Yeast Bread', era:'industrial', difficulty:'Easy', time:'3 hr',
    tagline:'Isolated, standardized yeast strains made bread rise predictably every time.',
    scienceTip:'Standardized Fermentation',
    steps:['Dissolve a measured packet of commercial yeast in warm water.','Mix into flour, salt, and a little sugar to form a dough.','Knead and let rise for about 90 minutes.','Shape, proof again, and bake at 220°C (425°F) for 30–35 minutes.'],
    science:'Unlike wild sourdough starters with unpredictable microbial mixes, a single isolated strain of Saccharomyces cerevisiae ferments at a known, consistent rate — the reason commercial bread rises so reliably.' },
  { id:'vacuum-sealed-smoked-meat', title:'Vacuum-Sealed Smoked Meat', era:'industrial', difficulty:'Medium', time:'8 hr',
    tagline:'Removing oxygen entirely extended smoked meat\u2019s shelf life even further.',
    scienceTip:'Oxidative Exclusion',
    steps:['Smoke cured meat low and slow for several hours as usual.','Cool completely.','Seal tightly in an oxygen-free vacuum pouch.','Store refrigerated.'],
    science:'Removing oxygen starves aerobic spoilage bacteria and halts fat oxidation, meaning smoked meat sealed this way resists both microbial spoilage and rancidity far longer than open-air storage allows.' },
  { id:'bottled-carbonated-soda', title:'Bottled Carbonated Soda', era:'industrial', difficulty:'Medium', time:'20 min',
    tagline:'Pressurized CO2 dissolved into flavored syrup created the first fizzy drinks.',
    scienceTip:'Gas Solubility Under Pressure',
    steps:['Mix flavored syrup with cold water.','Chill thoroughly.','Force carbon dioxide gas into the liquid under pressure.','Seal immediately in a pressure-rated bottle.'],
    science:'Gas solubility rises with pressure and falls with temperature, so cold, pressurized conditions force far more CO2 into solution than would ever dissolve at room temperature and normal atmospheric pressure.' },
  { id:'refined-sugar-cubes', title:'Refined White Sugar Cubes', era:'industrial', difficulty:'Medium', time:'2 hr',
    tagline:'Raw cane juice, purified and crystallized into a shelf-stable, near-pure product.',
    scienceTip:'Sucrose Crystallization',
    steps:['Clarify raw cane juice by heating and skimming impurities.','Evaporate the clarified liquid until supersaturated with sugar.','Seed with fine crystals to encourage uniform crystallization.','Press and cut the set sugar into cubes.'],
    science:'Once a sugar solution becomes supersaturated, sucrose molecules begin locking into an ordered crystal lattice around seed crystals — controlling that process is what separates smooth sugar from grainy sugar.' },
  { id:'tinned-sardines', title:'Tinned Sardines in Oil', era:'industrial', difficulty:'Medium', time:'1 hr',
    tagline:'Small fish, sealed under oil and heat, made shelf-stable for years.',
    scienceTip:'Combined Thermal + Lipid Preservation',
    steps:['Clean and lightly salt whole small fish.','Pack tightly into sterilized tins.','Cover completely with oil, leaving minimal headspace.','Seal and process in a pressure canner to reach sterilizing temperature.'],
    science:'The oil layer excludes oxygen from the fish\u2019s surface while the pressure-canning heat destroys spoilage organisms — two separate preservation mechanisms stacked in a single can.' },

  // ==================== MOLECULAR GASTRONOMY (10) ====================
  { id:'modern-fruit-caviar', title:'Modern Fruit Caviar', era:'modern', difficulty:'Advanced', time:'40 min',
    tagline:'Fruit juice, spherified into pearls that burst with a single bite.',
    scienceTip:'Spherification',
    steps:['Blend fruit juice with sodium alginate until fully dissolved; let rest to remove air bubbles.','Prepare a separate bath of water and calcium lactate.','Drop the juice mixture into the calcium bath using a syringe or pipette.','Let each sphere set for 2–3 minutes, then rinse gently in clean water.'],
    science:'Calcium ions cross-link alginate molecules into a gel skin the instant they touch, forming a thin membrane around liquid juice — a technique borrowed directly from food-industry chemistry in the early 2000s.' },
  { id:'sous-vide-egg', title:'Modern Sous-Vide Egg', era:'modern', difficulty:'Medium', time:'1 hr',
    tagline:'A water bath precise to the degree, for a texture no stovetop can match.',
    scienceTip:'Protein Denaturation Curves',
    steps:['Set a water bath to exactly 63°C (145°F) using an immersion circulator.','Lower whole eggs, still in their shells, into the bath.','Cook for 45–60 minutes without disturbing the temperature.','Remove and crack directly into a bowl.'],
    science:'Egg white and yolk proteins denature at different, very specific temperatures. Holding the bath a few degrees below the white\u2019s full-set point produces a texture impossible to hit consistently by boiling.' },
  { id:'reverse-spherification-yogurt', title:'Reverse Spherification Yogurt Pearls', era:'modern', difficulty:'Advanced', time:'45 min',
    tagline:'Flipping the spherification bath lets you set calcium-rich liquids like yogurt.',
    scienceTip:'Reverse Spherification',
    steps:['Blend yogurt with calcium lactate until smooth.','Prepare a separate bath of water and sodium alginate.','Drop the yogurt mixture into the alginate bath using a spoon or pipette.','Let set for 2–4 minutes, then rinse gently.'],
    science:'Classic spherification can\u2019t set calcium-rich liquids directly, since they clump the alginate on contact — reversing the setup, with calcium inside the drop and alginate in the bath, solves that entirely.' },
  { id:'liquid-nitrogen-ice-cream', title:'Liquid Nitrogen Ice Cream', era:'modern', difficulty:'Advanced', time:'15 min',
    tagline:'Instant freezing produces a texture no home freezer can replicate.',
    scienceTip:'Flash Freezing / Crystal Size Control',
    steps:['Prepare a standard custard-style ice cream base and chill it.','Pour liquid nitrogen slowly into the base while mixing continuously.','Continue mixing until fully frozen, roughly 1–2 minutes.','Serve immediately.'],
    science:'Extremely fast freezing gives water molecules no time to form large ice crystals, resulting in a far smoother texture than the slower freeze of a standard home ice-cream maker.' },
  { id:'hydrocolloid-vegetable-noodles', title:'Hydrocolloid Vegetable Noodles', era:'modern', difficulty:'Advanced', time:'50 min',
    tagline:'Pure vegetable juice, gelled into noodle shapes with no flour at all.',
    scienceTip:'Hydrocolloid Gelling',
    steps:['Blend and strain vegetables into a smooth juice.','Whisk in agar-agar powder and bring briefly to a boil.','Pour into long silicone tubes or a shallow tray.','Chill until set, then unmold or slice into noodle strands.'],
    science:'Agar sets into a firm gel on cooling below roughly 40°C, meaning pure vegetable liquid with no starch or gluten at all can still be shaped into something that holds together like a noodle.' },
  { id:'foamed-espresso-air', title:'Foamed Espresso Air', era:'modern', difficulty:'Medium', time:'15 min',
    tagline:'A cloud of pure coffee flavor with almost none of the liquid\u2019s weight.',
    scienceTip:'Lecithin-Stabilized Foam',
    steps:['Brew strong espresso and let cool slightly.','Whisk in a small amount of soy lecithin powder.','Use an immersion blender at the surface to whip in air.','Skim the resulting foam off the top to serve.'],
    science:'Lecithin\u2019s dual water-loving and air-loving structure lets it stabilize thin liquid films around air bubbles, holding an airy foam together far longer than the espresso could sustain on its own.' },
  { id:'sodium-alginate-olive-spheres', title:'Sodium Alginate Olive Spheres', era:'modern', difficulty:'Advanced', time:'40 min',
    tagline:'Concentrated olive juice, spherified into a savory burst — a signature El Bulli technique.',
    scienceTip:'Savory Spherification',
    steps:['Blend and strain olives into a smooth, concentrated liquid.','Mix with sodium alginate until dissolved.','Drop into a calcium chloride bath using a spoon.','Rinse gently in clean water before serving.'],
    science:'The same calcium-alginate gelling reaction used for sweet fruit caviar works identically on savory liquids — spherification cares about the ions present, not whether the result is dessert or garnish.' },
  { id:'xanthan-fruit-gel', title:'Xanthan-Thickened Fruit Gel', era:'modern', difficulty:'Medium', time:'20 min',
    tagline:'A pourable, glossy gel built without any heat at all.',
    scienceTip:'Cold Hydrocolloid Thickening',
    steps:['Blend fruit into a smooth puree.','Sprinkle xanthan gum over the puree while blending continuously.','Blend until fully thickened and smooth, with no lumps.','Chill briefly before serving.'],
    science:'Xanthan gum hydrates and thickens liquid at room temperature through its long, tangled polymer chains — unlike starch or gelatin, it needs no heat at all to reach full thickening power.' },
  { id:'dehydrated-fruit-leather', title:'Dehydrated Fruit Leather', era:'modern', difficulty:'Easy', time:'8 hr',
    tagline:'Slow, low-temperature drying concentrates fruit into a chewy, shelf-stable sheet.',
    scienceTip:'Controlled Osmotic Dehydration',
    steps:['Blend fruit into a smooth puree, sweetening if needed.','Spread thinly and evenly on a lined dehydrator tray.','Dry at a low temperature, around 57°C (135°F), for 6–8 hours.','Peel off and cut into strips once fully dried and pliable.'],
    science:'A precisely controlled low temperature removes water slowly enough that sugars concentrate evenly throughout the fruit rather than case-hardening a dry shell around a wet center, as high heat would.' },
  { id:'transglutaminase-meat-fusion', title:'Transglutaminase "Meat Glue" Fusion', era:'modern', difficulty:'Advanced', time:'24 hr',
    tagline:'An enzyme that welds two separate pieces of protein into one seamless cut.',
    scienceTip:'Enzymatic Protein Cross-Linking',
    steps:['Trim two pieces of raw meat to fit together cleanly.','Dust the contact surfaces evenly with transglutaminase powder.','Press the pieces firmly together and wrap tightly.','Refrigerate for 12–24 hours to let the bond fully form.'],
    science:'Transglutaminase catalyzes the formation of new covalent bonds directly between protein molecules across the two surfaces, fusing them at a molecular level rather than just holding them together mechanically.' },
];
