/* Timeline Portal — historical food-science milestones, filterable by era */
const MILESTONES = [
  { era:'neolithic', year:'~1,000,000–400,000 BCE', title:'Controlled Use of Fire',
    text:'Early humans learn to maintain and control fire, making cooking — and everything that follows from it — possible for the first time.' },
  { era:'neolithic', year:'~10,000 BCE', title:'Quern-Stone Grinding',
    text:'Flat grinding stones turn whole grain into usable flour, the mechanical step that makes flatbread and porridge possible.' },
  { era:'neolithic', year:'~9,500 BCE', title:'Grain Domestication Begins',
    text:'Wild wheat and barley are selectively planted and harvested in the Fertile Crescent, tying diet to agriculture for the first time.' },
  { era:'ancient', year:'~5,500 BCE', title:'Cheese-Making Established',
    text:'Early dairying cultures discover that rennet from animal stomachs curdles milk into a far more durable food than milk itself.' },
  { era:'ancient', year:'~3,000 BCE', title:'Leavened Bread in Egypt',
    text:'Wild airborne yeast, likely captured by accident in stored dough, produces the first reliably risen loaves.' },
  { era:'ancient', year:'~600 BCE', title:'Garum Fermentation Spreads',
    text:'Fermented fish sauce becomes a dominant seasoning across the Mediterranean, engineered entirely through salt and enzymatic patience.' },
  { era:'medieval', year:'~800–1200 CE', title:'Distillation Refined',
    text:'Arab and later European alchemists refine the still, separating alcohol from fermented liquid by exploiting differing boiling points.' },
  { era:'medieval', year:'~1000 CE', title:'Sugar Refining Spreads West',
    text:'Sugar refining techniques travel along spice-and-sugar trade routes, slowly shifting sugar from medicine to luxury sweetener.' },
  { era:'medieval', year:'~1200s CE', title:'Spice-Route Preservation',
    text:'Imported spices — pepper, clove, cinnamon — are prized not just for flavor but for their genuine antimicrobial preservative effects.' },
  { era:'industrial', year:'1809', title:'Canning Invented',
    text:'Nicolas Appert discovers that sealed, heated jars keep food edible for months — decades before germ theory explains why.' },
  { era:'industrial', year:'1864', title:'Pasteurization Discovered',
    text:'Louis Pasteur demonstrates that precise, moderate heating kills spoilage organisms in wine and milk without ruining the product.' },
  { era:'industrial', year:'1876', title:'Mechanical Refrigeration',
    text:'Practical mechanical refrigeration begins to replace ice houses, decoupling food preservation from climate and season for the first time.' },
  { era:'modern', year:'1969', title:'Sous-Vide Technique Emerges',
    text:'Precise, sealed low-temperature water-bath cooking is developed for industrial food processing, later adopted by fine dining.' },
  { era:'modern', year:'1988', title:'"Molecular Gastronomy" Coined',
    text:'Physicist Nicholas Kurti and chemist Hervé This coin the term, formally naming the scientific study of culinary transformations.' },
  { era:'modern', year:'2003', title:'Spherification Popularized',
    text:'Ferran Adrià\u2019s El Bulli popularizes calcium-alginate spherification, turning liquids into gel-skinned spheres that burst on the tongue.' },
];
